name: example
description: A Very Good Example for steering behaviors.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flame: ^1.2.0
  flame_behaviors: ^0.1.0
  flame_steering_behaviors:
    path: ../
  flutter:
    sdk: flutter
  mocktail: ^0.3.0

dev_dependencies:
  flame_test: ^1.5.0
  flutter_test:
    sdk: flutter
  very_good_analysis: ^4.0.0+1
