name: flame_steering_behaviors
description: An implementation of steering behaviors for Flame Behaviors.
version: 0.0.1-dev.0

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies: 
  flame: ^1.2.0
  flame_behaviors: ">=0.1.0 <0.3.0"
  flutter:
    sdk: flutter

dev_dependencies:
  flame_test: ^1.5.0
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^3.0.0
