name: steering_behaviors
description: Flame behaviors used to organically manage the movement of an entity
version: 0.0.1-dev.0

environment:
  sdk: ">=2.17.0 <3.0.0"

dev_dependencies:
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^3.0.0
